# Generated by Django 3.1.3 on 2020-11-20 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0002_remove_mealfav_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealrate',
            name='restaurant',
        ),
    ]
